# ftpsyn installation and configuration for lidsol.fi-b.unam.mx
---
- name: Ensure user mirrors exists
  ansible.builtin.user:
    name: mirrors
    state: present
    system: false

- name: Copy ftpsync directory as /home/mirrors/
  ansible.builtin.copy:
    src: files/ftpsync/
    dest: /home/mirrors/
    owner: mirrors
    group: mirrors
    mode: '0755'
