# Rsyncd install and configuration
---
- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present

- name: Copy rsyncd configuration file
  ansible.builtin.copy:
    src: files/rsync/rsyncd.conf
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure rsyncd service is enabled and running
  ansible.builtin.service:
    name: rsync
    enabled: true
    state: started
